server:
  port: 9999
spring:
  application:
    name: eureka-client
eureka:
  client:
    service-url:
      #      defaultZone: http://peer1:8761/eureka
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka,http://peer2:8763/eureka
